name: 'Link Check'
description: 'Check for broken links on a website using muffet'
author: 'mithro'

branding:
  icon: 'link'
  color: 'blue'

inputs:
  url:
    description: 'URL to check for broken links'
    required: true
  timeout:
    description: 'HTTP request timeout in seconds'
    required: false
    default: '30'
  max-connections:
    description: 'Maximum number of concurrent connections'
    required: false
    default: '10'
  max-connections-per-host:
    description: 'Maximum connections per host'
    required: false
    default: '5'
  buffer-size:
    description: 'Buffer size in bytes'
    required: false
    default: '16384'
  exclude:
    description: 'Newline-separated list of regex patterns to exclude'
    required: false
    default: |
      .*mailto:.*
      .*linkedin\.com.*
  include-browser-headers:
    description: 'Include Chrome-like browser headers'
    required: false
    default: 'true'
  max-redirects:
    description: 'Maximum number of redirects to follow'
    required: false
    default: '10'
  skip-tls-verification:
    description: 'Skip TLS certificate verification'
    required: false
    default: 'false'
  fail-on-error:
    description: 'Fail the workflow if broken links are found'
    required: false
    default: 'true'
  verbose:
    description: 'Show all checked URLs, not just failures'
    required: false
    default: 'false'

  # Wait-for-ready inputs
  wait-for-url:
    description: 'Wait for the URL to be accessible (HTTP 200) before checking links'
    required: false
    default: 'false'
  wait-for-content:
    description: 'Wait for specific content to appear in the page (regex pattern). Implies wait-for-url.'
    required: false
    default: ''
  wait-timeout:
    description: 'Maximum time to wait for URL/content in seconds'
    required: false
    default: '300'
  wait-interval:
    description: 'Time between retry attempts in seconds'
    required: false
    default: '5'

outputs:
  success:
    description: 'Whether all links are valid (true/false)'
  broken-links-count:
    description: 'Number of broken links found'
  report-path:
    description: 'Path to the detailed report file'

runs:
  using: 'node20'
  main: 'dist/index.js'
