# Example for checking PR preview deployments
name: Link Check PR Preview

on:
  pull_request:
    branches: [main]

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for preview deployment
        run: |
          echo "Waiting for preview deployment..."
          sleep 60

      - uses: mithro/linkcheck-action@main
        id: linkcheck
        with:
          url: 'https://preview.your-site.com/pr-${{ github.event.pull_request.number }}/'
          fail-on-error: 'false'

      - name: Comment on PR
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const success = '${{ steps.linkcheck.outputs.success }}' === 'true';
            const brokenCount = '${{ steps.linkcheck.outputs.broken-links-count }}';

            const body = success
              ? '## Link Check Results\n\n:white_check_mark: All links are valid!'
              : `## Link Check Results\n\n:x: Found ${brokenCount} broken links. See workflow run for details.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
